CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218191624_InitialIdentityCreate') THEN
    CREATE TABLE "AuditLogs" (
        "Id" uuid NOT NULL,
        "UserId" uuid,
        "Action" character varying(100) NOT NULL,
        "EntityType" character varying(100),
        "EntityId" uuid,
        "Changes" character varying(4000),
        "IpAddress" character varying(45),
        "UserAgent" character varying(500),
        "Timestamp" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218191624_InitialIdentityCreate') THEN
    CREATE TABLE "LoginAttempts" (
        "Id" uuid NOT NULL,
        "UserId" uuid,
        "Username" character varying(50),
        "IpAddress" character varying(45),
        "UserAgent" character varying(500),
        "Success" boolean NOT NULL,
        "FailureReason" character varying(255),
        "AttemptedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_LoginAttempts" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218191624_InitialIdentityCreate') THEN
    CREATE TABLE "Permissions" (
        "Id" uuid NOT NULL,
        "Name" character varying(100) NOT NULL,
        "Description" character varying(255),
        "Category" character varying(50),
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Permissions" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218191624_InitialIdentityCreate') THEN
    CREATE TABLE "Roles" (
        "Id" uuid NOT NULL,
        "Description" character varying(255),
        "IsSystemRole" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218191624_InitialIdentityCreate') THEN
    CREATE TABLE "Users" (
        "Id" uuid NOT NULL,
        "FirstName" character varying(100),
        "LastName" character varying(100),
        "IsActive" boolean NOT NULL,
        "RequirePasswordChange" boolean NOT NULL,
        "MfaEnabled" boolean NOT NULL,
        "LastLoginDate" timestamp with time zone,
        "LastPasswordChangeDate" timestamp with time zone NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "DeletedAt" timestamp with time zone,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218191624_InitialIdentityCreate') THEN
    CREATE TABLE "RoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" uuid NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_RoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RoleClaims_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218191624_InitialIdentityCreate') THEN
    CREATE TABLE "RolePermissions" (
        "RoleId" uuid NOT NULL,
        "PermissionId" uuid NOT NULL,
        CONSTRAINT "PK_RolePermissions" PRIMARY KEY ("RoleId", "PermissionId"),
        CONSTRAINT "FK_RolePermissions_Permissions_PermissionId" FOREIGN KEY ("PermissionId") REFERENCES "Permissions" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_RolePermissions_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218191624_InitialIdentityCreate') THEN
    CREATE TABLE "Devices" (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "DeviceId" character varying(255) NOT NULL,
        "DeviceName" character varying(100) NOT NULL,
        "DeviceType" character varying(50) NOT NULL,
        "DeviceModel" character varying(100),
        "FirmwareVersion" character varying(50),
        "CreatedAt" timestamp with time zone NOT NULL,
        "LastUsedAt" timestamp with time zone,
        "RevokedAt" timestamp with time zone,
        "RevokedReason" character varying(255),
        "RevokedBy" uuid,
        "IsActive" boolean NOT NULL,
        "CreatedByIp" character varying(45),
        "LastUsedIp" character varying(45),
        CONSTRAINT "PK_Devices" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Devices_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218191624_InitialIdentityCreate') THEN
    CREATE TABLE "EmailChangeTokens" (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "Token" character varying(500) NOT NULL,
        "NewEmail" character varying(255) NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "VerifiedAt" timestamp with time zone,
        CONSTRAINT "PK_EmailChangeTokens" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_EmailChangeTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218191624_InitialIdentityCreate') THEN
    CREATE TABLE "EmailVerificationTokens" (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "Token" character varying(500) NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "VerifiedAt" timestamp with time zone,
        CONSTRAINT "PK_EmailVerificationTokens" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_EmailVerificationTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218191624_InitialIdentityCreate') THEN
    CREATE TABLE "MfaConfigurations" (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "MfaType" character varying(20) NOT NULL,
        "SecretKey" character varying(500),
        "PhoneNumber" character varying(20),
        "PhoneNumberConfirmed" boolean NOT NULL,
        "BackupCodes" character varying(2000),
        "IsEnabled" boolean NOT NULL,
        "PreferredMethod" character varying(20),
        "CreatedAt" timestamp with time zone NOT NULL,
        "EnabledAt" timestamp with time zone,
        "LastUsedAt" timestamp with time zone,
        CONSTRAINT "PK_MfaConfigurations" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_MfaConfigurations_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218191624_InitialIdentityCreate') THEN
    CREATE TABLE "PasswordHistories" (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "PasswordHash" character varying(500) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_PasswordHistories" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PasswordHistories_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218191624_InitialIdentityCreate') THEN
    CREATE TABLE "PasswordResetTokens" (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "Token" character varying(500) NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UsedAt" timestamp with time zone,
        CONSTRAINT "PK_PasswordResetTokens" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PasswordResetTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218191624_InitialIdentityCreate') THEN
    CREATE TABLE "SmsVerifications" (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "PhoneNumber" character varying(20) NOT NULL,
        "Code" character varying(100) NOT NULL,
        "Purpose" character varying(50) NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "AttemptCount" integer NOT NULL,
        "VerifiedAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        "IpAddress" character varying(45),
        "TwilioMessageSid" character varying(50),
        "TwilioStatus" character varying(20),
        CONSTRAINT "PK_SmsVerifications" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SmsVerifications_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218191624_InitialIdentityCreate') THEN
    CREATE TABLE "UserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" uuid NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_UserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_UserClaims_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218191624_InitialIdentityCreate') THEN
    CREATE TABLE "UserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" uuid NOT NULL,
        CONSTRAINT "PK_UserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_UserLogins_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218191624_InitialIdentityCreate') THEN
    CREATE TABLE "UserRoles" (
        "UserId" uuid NOT NULL,
        "RoleId" uuid NOT NULL,
        "AssignedAt" timestamp with time zone NOT NULL,
        "AssignedBy" uuid,
        CONSTRAINT "PK_UserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_UserRoles_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_UserRoles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218191624_InitialIdentityCreate') THEN
    CREATE TABLE "UserTokens" (
        "UserId" uuid NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_UserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_UserTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218191624_InitialIdentityCreate') THEN
    CREATE TABLE "RefreshTokens" (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "Token" character varying(500) NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "RevokedAt" timestamp with time zone,
        "ReplacedByToken" character varying(500),
        "ReasonRevoked" character varying(255),
        "CreatedByIp" character varying(45),
        "RevokedByIp" character varying(45),
        "DeviceInternalId" uuid,
        CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RefreshTokens_Devices_DeviceInternalId" FOREIGN KEY ("DeviceInternalId") REFERENCES "Devices" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_RefreshTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218191624_InitialIdentityCreate') THEN
    INSERT INTO "Roles" ("Id", "ConcurrencyStamp", "CreatedAt", "Description", "IsSystemRole", "Name", "NormalizedName", "UpdatedAt")
    VALUES ('00000000-0000-0000-0000-000000000001', '6e6495cc-b924-4bbd-ad7c-e95b39515017', TIMESTAMPTZ '2024-01-01T00:00:00Z', 'System Administrator', TRUE, 'Admin', 'ADMIN', TIMESTAMPTZ '2024-01-01T00:00:00Z');
    INSERT INTO "Roles" ("Id", "ConcurrencyStamp", "CreatedAt", "Description", "IsSystemRole", "Name", "NormalizedName", "UpdatedAt")
    VALUES ('00000000-0000-0000-0000-000000000002', 'be874a1b-5a1e-49a1-b3ca-8d4f428c68b8', TIMESTAMPTZ '2024-01-01T00:00:00Z', 'Standard User', TRUE, 'User', 'USER', TIMESTAMPTZ '2024-01-01T00:00:00Z');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218191624_InitialIdentityCreate') THEN
    CREATE INDEX "IX_AuditLogs_Action" ON "AuditLogs" ("Action");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218191624_InitialIdentityCreate') THEN
    CREATE INDEX "IX_AuditLogs_Timestamp" ON "AuditLogs" ("Timestamp");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218191624_InitialIdentityCreate') THEN
    CREATE INDEX "IX_AuditLogs_UserId" ON "AuditLogs" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218191624_InitialIdentityCreate') THEN
    CREATE UNIQUE INDEX "IX_Devices_DeviceId_UserId" ON "Devices" ("DeviceId", "UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218191624_InitialIdentityCreate') THEN
    CREATE INDEX "IX_Devices_UserId" ON "Devices" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218191624_InitialIdentityCreate') THEN
    CREATE UNIQUE INDEX "IX_EmailChangeTokens_Token" ON "EmailChangeTokens" ("Token");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218191624_InitialIdentityCreate') THEN
    CREATE INDEX "IX_EmailChangeTokens_UserId" ON "EmailChangeTokens" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218191624_InitialIdentityCreate') THEN
    CREATE UNIQUE INDEX "IX_EmailVerificationTokens_Token" ON "EmailVerificationTokens" ("Token");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218191624_InitialIdentityCreate') THEN
    CREATE INDEX "IX_EmailVerificationTokens_UserId" ON "EmailVerificationTokens" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218191624_InitialIdentityCreate') THEN
    CREATE INDEX "IX_LoginAttempts_AttemptedAt" ON "LoginAttempts" ("AttemptedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218191624_InitialIdentityCreate') THEN
    CREATE INDEX "IX_LoginAttempts_IpAddress" ON "LoginAttempts" ("IpAddress");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218191624_InitialIdentityCreate') THEN
    CREATE INDEX "IX_LoginAttempts_UserId" ON "LoginAttempts" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218191624_InitialIdentityCreate') THEN
    CREATE UNIQUE INDEX "IX_MfaConfigurations_UserId" ON "MfaConfigurations" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218191624_InitialIdentityCreate') THEN
    CREATE INDEX "IX_PasswordHistories_UserId" ON "PasswordHistories" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218191624_InitialIdentityCreate') THEN
    CREATE UNIQUE INDEX "IX_PasswordResetTokens_Token" ON "PasswordResetTokens" ("Token");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218191624_InitialIdentityCreate') THEN
    CREATE INDEX "IX_PasswordResetTokens_UserId" ON "PasswordResetTokens" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218191624_InitialIdentityCreate') THEN
    CREATE UNIQUE INDEX "IX_Permissions_Name" ON "Permissions" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218191624_InitialIdentityCreate') THEN
    CREATE INDEX "IX_RefreshTokens_DeviceInternalId" ON "RefreshTokens" ("DeviceInternalId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218191624_InitialIdentityCreate') THEN
    CREATE INDEX "IX_RefreshTokens_Token" ON "RefreshTokens" ("Token");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218191624_InitialIdentityCreate') THEN
    CREATE INDEX "IX_RefreshTokens_UserId" ON "RefreshTokens" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218191624_InitialIdentityCreate') THEN
    CREATE INDEX "IX_RoleClaims_RoleId" ON "RoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218191624_InitialIdentityCreate') THEN
    CREATE INDEX "IX_RolePermissions_PermissionId" ON "RolePermissions" ("PermissionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218191624_InitialIdentityCreate') THEN
    CREATE UNIQUE INDEX "IX_Roles_Name" ON "Roles" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218191624_InitialIdentityCreate') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON "Roles" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218191624_InitialIdentityCreate') THEN
    CREATE INDEX "IX_SmsVerifications_PhoneNumber" ON "SmsVerifications" ("PhoneNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218191624_InitialIdentityCreate') THEN
    CREATE INDEX "IX_SmsVerifications_UserId" ON "SmsVerifications" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218191624_InitialIdentityCreate') THEN
    CREATE INDEX "IX_UserClaims_UserId" ON "UserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218191624_InitialIdentityCreate') THEN
    CREATE INDEX "IX_UserLogins_UserId" ON "UserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218191624_InitialIdentityCreate') THEN
    CREATE INDEX "IX_UserRoles_RoleId" ON "UserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218191624_InitialIdentityCreate') THEN
    CREATE INDEX "EmailIndex" ON "Users" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218191624_InitialIdentityCreate') THEN
    CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218191624_InitialIdentityCreate') THEN
    CREATE UNIQUE INDEX "IX_Users_UserName" ON "Users" ("UserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218191624_InitialIdentityCreate') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON "Users" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218191624_InitialIdentityCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251218191624_InitialIdentityCreate', '10.0.1');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222024200_AddDeviceGatewayEntities') THEN
    ALTER TABLE "Devices" ADD "LastSeenAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222024200_AddDeviceGatewayEntities') THEN
    ALTER TABLE "Devices" ADD "TenantId" uuid;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222024200_AddDeviceGatewayEntities') THEN
    ALTER TABLE "AuditLogs" ADD "CorrelationId" character varying(50);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222024200_AddDeviceGatewayEntities') THEN
    ALTER TABLE "AuditLogs" ADD "Details" character varying(4000);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222024200_AddDeviceGatewayEntities') THEN
    CREATE TABLE "DeviceCommands" (
        "Id" uuid NOT NULL,
        "DeviceId" uuid NOT NULL,
        "CommandType" character varying(50) NOT NULL,
        "Parameters" character varying(4000),
        "IssuedAt" timestamp with time zone NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "AcknowledgedAt" timestamp with time zone,
        "CompletedAt" timestamp with time zone,
        "Status" character varying(20) NOT NULL,
        "ErrorMessage" character varying(1000),
        "CreatedBy" uuid,
        CONSTRAINT "PK_DeviceCommands" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_DeviceCommands_Devices_DeviceId" FOREIGN KEY ("DeviceId") REFERENCES "Devices" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222024200_AddDeviceGatewayEntities') THEN
    CREATE TABLE "DeviceConfigurations" (
        "Id" uuid NOT NULL,
        "DeviceId" uuid NOT NULL,
        "Version" integer NOT NULL,
        "ConfigurationJson" text NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "UpdatedBy" uuid,
        CONSTRAINT "PK_DeviceConfigurations" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_DeviceConfigurations_Devices_DeviceId" FOREIGN KEY ("DeviceId") REFERENCES "Devices" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222024200_AddDeviceGatewayEntities') THEN
    CREATE TABLE "DeviceHeartbeats" (
        "Id" uuid NOT NULL,
        "DeviceId" uuid NOT NULL,
        "ClientVersion" character varying(50) NOT NULL,
        "UptimeSeconds" bigint NOT NULL,
        "QueueDepth" integer NOT NULL,
        "LastSyncUtc" timestamp with time zone NOT NULL,
        "ActiveSessionCount" integer NOT NULL,
        "ConnectionMode" character varying(20) NOT NULL,
        "ConfigVersion" integer NOT NULL,
        "HardwareTier" character varying(20) NOT NULL,
        "NetworkSpeed" character varying(20) NOT NULL,
        "ReceivedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_DeviceHeartbeats" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_DeviceHeartbeats_Devices_DeviceId" FOREIGN KEY ("DeviceId") REFERENCES "Devices" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222024200_AddDeviceGatewayEntities') THEN
    CREATE TABLE "Tenants" (
        "Id" uuid NOT NULL,
        "Name" character varying(100) NOT NULL,
        "OwnerId" uuid NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Tenants" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Tenants_Users_OwnerId" FOREIGN KEY ("OwnerId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222024200_AddDeviceGatewayEntities') THEN
    CREATE TABLE "MonitoringBatches" (
        "Id" uuid NOT NULL,
        "BatchId" character varying(100) NOT NULL,
        "DeviceId" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "SessionId" integer NOT NULL,
        "S3Path" character varying(500) NOT NULL,
        "CompressedSize" bigint NOT NULL,
        "DecompressedSize" bigint NOT NULL,
        "CompressionAlgorithm" character varying(20) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "ReceivedAt" timestamp with time zone NOT NULL,
        "CorrelationId" character varying(50),
        "DeletedAt" timestamp with time zone,
        "RabbitMqPublished" boolean NOT NULL,
        CONSTRAINT "PK_MonitoringBatches" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_MonitoringBatches_Devices_DeviceId" FOREIGN KEY ("DeviceId") REFERENCES "Devices" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_MonitoringBatches_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222024200_AddDeviceGatewayEntities') THEN
    CREATE TABLE "TenantMembers" (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "Role" character varying(20) NOT NULL,
        "JoinedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_TenantMembers" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_TenantMembers_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_TenantMembers_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222024200_AddDeviceGatewayEntities') THEN
    UPDATE "Roles" SET "ConcurrencyStamp" = '592c0ac3-3844-4582-aa35-e77af544aa89'
    WHERE "Id" = '00000000-0000-0000-0000-000000000001';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222024200_AddDeviceGatewayEntities') THEN
    UPDATE "Roles" SET "ConcurrencyStamp" = 'af8e94ef-0e9f-4e5e-a6d8-98f8b2f764d1'
    WHERE "Id" = '00000000-0000-0000-0000-000000000002';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222024200_AddDeviceGatewayEntities') THEN
    CREATE INDEX "IX_Devices_LastSeenAt" ON "Devices" ("LastSeenAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222024200_AddDeviceGatewayEntities') THEN
    CREATE INDEX "IX_Devices_TenantId" ON "Devices" ("TenantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222024200_AddDeviceGatewayEntities') THEN
    CREATE INDEX "IX_AuditLogs_CorrelationId" ON "AuditLogs" ("CorrelationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222024200_AddDeviceGatewayEntities') THEN
    CREATE INDEX "IX_AuditLogs_EntityType_EntityId" ON "AuditLogs" ("EntityType", "EntityId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222024200_AddDeviceGatewayEntities') THEN
    CREATE INDEX "IX_DeviceCommands_DeviceId" ON "DeviceCommands" ("DeviceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222024200_AddDeviceGatewayEntities') THEN
    CREATE INDEX "IX_DeviceCommands_DeviceId_Status" ON "DeviceCommands" ("DeviceId", "Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222024200_AddDeviceGatewayEntities') THEN
    CREATE INDEX "IX_DeviceCommands_ExpiresAt" ON "DeviceCommands" ("ExpiresAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222024200_AddDeviceGatewayEntities') THEN
    CREATE INDEX "IX_DeviceCommands_IssuedAt" ON "DeviceCommands" ("IssuedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222024200_AddDeviceGatewayEntities') THEN
    CREATE UNIQUE INDEX "IX_DeviceConfigurations_DeviceId" ON "DeviceConfigurations" ("DeviceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222024200_AddDeviceGatewayEntities') THEN
    CREATE INDEX "IX_DeviceHeartbeats_DeviceId" ON "DeviceHeartbeats" ("DeviceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222024200_AddDeviceGatewayEntities') THEN
    CREATE INDEX "IX_DeviceHeartbeats_DeviceId_ReceivedAt" ON "DeviceHeartbeats" ("DeviceId", "ReceivedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222024200_AddDeviceGatewayEntities') THEN
    CREATE INDEX "IX_MonitoringBatches_CorrelationId" ON "MonitoringBatches" ("CorrelationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222024200_AddDeviceGatewayEntities') THEN
    CREATE UNIQUE INDEX "IX_MonitoringBatches_DeviceId_BatchId" ON "MonitoringBatches" ("DeviceId", "BatchId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222024200_AddDeviceGatewayEntities') THEN
    CREATE INDEX "IX_MonitoringBatches_RabbitMqPublished" ON "MonitoringBatches" ("RabbitMqPublished");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222024200_AddDeviceGatewayEntities') THEN
    CREATE INDEX "IX_MonitoringBatches_ReceivedAt" ON "MonitoringBatches" ("ReceivedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222024200_AddDeviceGatewayEntities') THEN
    CREATE INDEX "IX_MonitoringBatches_TenantId" ON "MonitoringBatches" ("TenantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222024200_AddDeviceGatewayEntities') THEN
    CREATE UNIQUE INDEX "IX_TenantMembers_TenantId_UserId" ON "TenantMembers" ("TenantId", "UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222024200_AddDeviceGatewayEntities') THEN
    CREATE INDEX "IX_TenantMembers_UserId" ON "TenantMembers" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222024200_AddDeviceGatewayEntities') THEN
    CREATE INDEX "IX_Tenants_OwnerId" ON "Tenants" ("OwnerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222024200_AddDeviceGatewayEntities') THEN
    ALTER TABLE "Devices" ADD CONSTRAINT "FK_Devices_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222024200_AddDeviceGatewayEntities') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251222024200_AddDeviceGatewayEntities', '10.0.1');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222190251_AddContentHashToMonitoringBatch') THEN
    DROP INDEX "IX_MonitoringBatches_RabbitMqPublished";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222190251_AddContentHashToMonitoringBatch') THEN
    DROP INDEX "IX_DeviceCommands_ExpiresAt";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222190251_AddContentHashToMonitoringBatch') THEN
    ALTER TABLE "MonitoringBatches" ADD "ContentHash" character varying(64);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222190251_AddContentHashToMonitoringBatch') THEN
    UPDATE "Roles" SET "ConcurrencyStamp" = '00000000-0000-0000-0000-000000000001'
    WHERE "Id" = '00000000-0000-0000-0000-000000000001';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222190251_AddContentHashToMonitoringBatch') THEN
    UPDATE "Roles" SET "ConcurrencyStamp" = '00000000-0000-0000-0000-000000000002'
    WHERE "Id" = '00000000-0000-0000-0000-000000000002';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222190251_AddContentHashToMonitoringBatch') THEN
    CREATE INDEX "IX_MonitoringBatches_DeviceId_ContentHash" ON "MonitoringBatches" ("DeviceId", "ContentHash");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222190251_AddContentHashToMonitoringBatch') THEN
    CREATE INDEX "IX_MonitoringBatches_RabbitMqPublished" ON "MonitoringBatches" ("RabbitMqPublished") WHERE "RabbitMqPublished" = false;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222190251_AddContentHashToMonitoringBatch') THEN
    CREATE INDEX "IX_DeviceCommands_ExpiresAt" ON "DeviceCommands" ("ExpiresAt") WHERE "Status" = 'pending';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222190251_AddContentHashToMonitoringBatch') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251222190251_AddContentHashToMonitoringBatch', '10.0.1');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251225154135_AddMonitoringConfigEntities') THEN
    ALTER TABLE "DeviceConfigurations" DROP COLUMN "ConfigurationJson";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251225154135_AddMonitoringConfigEntities') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'tgp') THEN
            CREATE SCHEMA tgp;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251225154135_AddMonitoringConfigEntities') THEN
    ALTER TABLE "UserTokens" SET SCHEMA tgp;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251225154135_AddMonitoringConfigEntities') THEN
    ALTER TABLE "Users" SET SCHEMA tgp;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251225154135_AddMonitoringConfigEntities') THEN
    ALTER TABLE "UserRoles" SET SCHEMA tgp;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251225154135_AddMonitoringConfigEntities') THEN
    ALTER TABLE "UserLogins" SET SCHEMA tgp;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251225154135_AddMonitoringConfigEntities') THEN
    ALTER TABLE "UserClaims" SET SCHEMA tgp;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251225154135_AddMonitoringConfigEntities') THEN
    ALTER TABLE "Tenants" SET SCHEMA tgp;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251225154135_AddMonitoringConfigEntities') THEN
    ALTER TABLE "TenantMembers" SET SCHEMA tgp;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251225154135_AddMonitoringConfigEntities') THEN
    ALTER TABLE "SmsVerifications" SET SCHEMA tgp;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251225154135_AddMonitoringConfigEntities') THEN
    ALTER TABLE "Roles" SET SCHEMA tgp;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251225154135_AddMonitoringConfigEntities') THEN
    ALTER TABLE "RolePermissions" SET SCHEMA tgp;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251225154135_AddMonitoringConfigEntities') THEN
    ALTER TABLE "RoleClaims" SET SCHEMA tgp;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251225154135_AddMonitoringConfigEntities') THEN
    ALTER TABLE "RefreshTokens" SET SCHEMA tgp;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251225154135_AddMonitoringConfigEntities') THEN
    ALTER TABLE "Permissions" SET SCHEMA tgp;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251225154135_AddMonitoringConfigEntities') THEN
    ALTER TABLE "PasswordResetTokens" SET SCHEMA tgp;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251225154135_AddMonitoringConfigEntities') THEN
    ALTER TABLE "PasswordHistories" SET SCHEMA tgp;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251225154135_AddMonitoringConfigEntities') THEN
    ALTER TABLE "MonitoringBatches" SET SCHEMA tgp;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251225154135_AddMonitoringConfigEntities') THEN
    ALTER TABLE "MfaConfigurations" SET SCHEMA tgp;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251225154135_AddMonitoringConfigEntities') THEN
    ALTER TABLE "LoginAttempts" SET SCHEMA tgp;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251225154135_AddMonitoringConfigEntities') THEN
    ALTER TABLE "EmailVerificationTokens" SET SCHEMA tgp;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251225154135_AddMonitoringConfigEntities') THEN
    ALTER TABLE "EmailChangeTokens" SET SCHEMA tgp;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251225154135_AddMonitoringConfigEntities') THEN
    ALTER TABLE "Devices" SET SCHEMA tgp;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251225154135_AddMonitoringConfigEntities') THEN
    ALTER TABLE "DeviceHeartbeats" SET SCHEMA tgp;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251225154135_AddMonitoringConfigEntities') THEN
    ALTER TABLE "DeviceConfigurations" SET SCHEMA tgp;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251225154135_AddMonitoringConfigEntities') THEN
    ALTER TABLE "DeviceCommands" SET SCHEMA tgp;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251225154135_AddMonitoringConfigEntities') THEN
    ALTER TABLE "AuditLogs" SET SCHEMA tgp;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251225154135_AddMonitoringConfigEntities') THEN
    ALTER TABLE tgp."DeviceConfigurations" ADD "MaxRetryAttempts" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251225154135_AddMonitoringConfigEntities') THEN
    ALTER TABLE tgp."DeviceConfigurations" ADD "PollingIntervalSeconds" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251225154135_AddMonitoringConfigEntities') THEN
    ALTER TABLE tgp."DeviceConfigurations" ADD "RetryBaseDelaySeconds" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251225154135_AddMonitoringConfigEntities') THEN
    ALTER TABLE tgp."DeviceConfigurations" ADD "RetryMaxDelaySeconds" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251225154135_AddMonitoringConfigEntities') THEN
    ALTER TABLE tgp."DeviceConfigurations" ADD "TimezoneOffsetMinutes" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251225154135_AddMonitoringConfigEntities') THEN
    CREATE TABLE tgp."DetectedUsers" (
        "Id" uuid NOT NULL,
        "DeviceId" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "Username" character varying(100) NOT NULL,
        "SessionId" integer,
        "DetectedAt" timestamp with time zone NOT NULL,
        "IsReviewed" boolean NOT NULL,
        "ReviewedAt" timestamp with time zone,
        "ReviewedBy" uuid,
        CONSTRAINT "PK_DetectedUsers" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_DetectedUsers_Devices_DeviceId" FOREIGN KEY ("DeviceId") REFERENCES tgp."Devices" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_DetectedUsers_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES tgp."Tenants" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251225154135_AddMonitoringConfigEntities') THEN
    CREATE TABLE tgp."FallbackUrls" (
        "Id" uuid NOT NULL,
        "Url" character varying(500) NOT NULL,
        "Priority" integer NOT NULL,
        "IsEnabled" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_FallbackUrls" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251225154135_AddMonitoringConfigEntities') THEN
    CREATE TABLE tgp."GlobalSettings" (
        "Id" uuid NOT NULL,
        "Key" character varying(100) NOT NULL,
        "Value" character varying(4000) NOT NULL,
        "Description" character varying(500),
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_GlobalSettings" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251225154135_AddMonitoringConfigEntities') THEN
    CREATE TABLE tgp."MonitoredUsers" (
        "Id" uuid NOT NULL,
        "DeviceId" uuid NOT NULL,
        "Username" character varying(100) NOT NULL,
        "SessionId" integer,
        "IsEnabled" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_MonitoredUsers" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_MonitoredUsers_Devices_DeviceId" FOREIGN KEY ("DeviceId") REFERENCES tgp."Devices" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251225154135_AddMonitoringConfigEntities') THEN
    CREATE TABLE tgp."MonitoredUserSettings" (
        "Id" uuid NOT NULL,
        "MonitoredUserId" uuid NOT NULL,
        "EnableProcessMonitoring" boolean NOT NULL,
        "EnableBrowserMonitoring" boolean NOT NULL,
        "EnableInputMonitoring" boolean NOT NULL,
        "EnableScreenCapture" boolean NOT NULL,
        "EnableLocationMonitoring" boolean NOT NULL,
        "ScreenCaptureIntervalSeconds" integer,
        "BlockedAppsJson" character varying(4000),
        "BlockedDomainsJson" character varying(4000),
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_MonitoredUserSettings" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_MonitoredUserSettings_MonitoredUsers_MonitoredUserId" FOREIGN KEY ("MonitoredUserId") REFERENCES tgp."MonitoredUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251225154135_AddMonitoringConfigEntities') THEN
    CREATE UNIQUE INDEX "IX_DetectedUsers_DeviceId_Username" ON tgp."DetectedUsers" ("DeviceId", "Username");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251225154135_AddMonitoringConfigEntities') THEN
    CREATE INDEX "IX_DetectedUsers_TenantId" ON tgp."DetectedUsers" ("TenantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251225154135_AddMonitoringConfigEntities') THEN
    CREATE INDEX "IX_DetectedUsers_TenantId_IsReviewed" ON tgp."DetectedUsers" ("TenantId", "IsReviewed");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251225154135_AddMonitoringConfigEntities') THEN
    CREATE INDEX "IX_FallbackUrls_IsEnabled" ON tgp."FallbackUrls" ("IsEnabled");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251225154135_AddMonitoringConfigEntities') THEN
    CREATE INDEX "IX_FallbackUrls_Priority" ON tgp."FallbackUrls" ("Priority");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251225154135_AddMonitoringConfigEntities') THEN
    CREATE UNIQUE INDEX "IX_GlobalSettings_Key" ON tgp."GlobalSettings" ("Key");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251225154135_AddMonitoringConfigEntities') THEN
    CREATE UNIQUE INDEX "IX_MonitoredUsers_DeviceId_Username" ON tgp."MonitoredUsers" ("DeviceId", "Username");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251225154135_AddMonitoringConfigEntities') THEN
    CREATE UNIQUE INDEX "IX_MonitoredUserSettings_MonitoredUserId" ON tgp."MonitoredUserSettings" ("MonitoredUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251225154135_AddMonitoringConfigEntities') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251225154135_AddMonitoringConfigEntities', '10.0.1');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251225154222_SeedGlobalSettings') THEN
    INSERT INTO tgp."GlobalSettings" ("Id", "Description", "Key", "UpdatedAt", "Value")
    VALUES ('00000000-0000-0000-0000-000000000010', 'SignalR hub URL for device connections', 'SignalRHubUrl', TIMESTAMPTZ '2024-01-01T00:00:00Z', 'wss://gateway.tgp.com/hubs/v1/windows/device');
    INSERT INTO tgp."GlobalSettings" ("Id", "Description", "Key", "UpdatedAt", "Value")
    VALUES ('00000000-0000-0000-0000-000000000011', 'Default polling interval for devices in seconds', 'DefaultPollingIntervalSeconds', TIMESTAMPTZ '2024-01-01T00:00:00Z', '30');
    INSERT INTO tgp."GlobalSettings" ("Id", "Description", "Key", "UpdatedAt", "Value")
    VALUES ('00000000-0000-0000-0000-000000000012', 'Default maximum retry attempts for failed requests', 'DefaultMaxRetryAttempts', TIMESTAMPTZ '2024-01-01T00:00:00Z', '3');
    INSERT INTO tgp."GlobalSettings" ("Id", "Description", "Key", "UpdatedAt", "Value")
    VALUES ('00000000-0000-0000-0000-000000000013', 'Default base delay in seconds for retry backoff', 'DefaultRetryBaseDelaySeconds', TIMESTAMPTZ '2024-01-01T00:00:00Z', '5');
    INSERT INTO tgp."GlobalSettings" ("Id", "Description", "Key", "UpdatedAt", "Value")
    VALUES ('00000000-0000-0000-0000-000000000014', 'Default maximum delay in seconds for retry backoff', 'DefaultRetryMaxDelaySeconds', TIMESTAMPTZ '2024-01-01T00:00:00Z', '60');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251225154222_SeedGlobalSettings') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251225154222_SeedGlobalSettings', '10.0.1');
    END IF;
END $EF$;
COMMIT;

